In [19]:
import torch

from myPosEnc import PositionEncoding2D

In [20]:
img = torch.arange(start=0, end=24, dtype=torch.float32).reshape((4,6))

print(img)
print(img.shape)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])
torch.Size([4, 6])


In [21]:
torch.permute(img.reshape((2, 2, 2, 3)), (0, 2, 1, 3))

tensor([[[[ 0.,  1.,  2.],
          [ 6.,  7.,  8.]],

         [[ 3.,  4.,  5.],
          [ 9., 10., 11.]]],


        [[[12., 13., 14.],
          [18., 19., 20.]],

         [[15., 16., 17.],
          [21., 22., 23.]]]])

In [22]:
img_patch = torch.reshape(torch.permute(img.reshape((2, 2, 2, 3)), (0, 2, 1, 3)), (4, 6))
img_patch

tensor([[ 0.,  1.,  2.,  6.,  7.,  8.],
        [ 3.,  4.,  5.,  9., 10., 11.],
        [12., 13., 14., 18., 19., 20.],
        [15., 16., 17., 21., 22., 23.]])

In [30]:
torch.manual_seed(724)

img_patch_embed = img_patch @ (torch.rand(size=(6, 32), dtype=torch.float32) - 0.5)

print(img_patch_embed.shape)
print(img_patch_embed)

torch.Size([4, 32])
tensor([[ -1.6705,  -4.3936,   0.7323,  -0.4634,  -4.6863,  -6.2770,   1.6267,
          -0.6153,  -6.3250,  -1.2190,   2.2540,   4.1469,   0.3836,   2.7370,
          -2.2485,  -5.4315,   3.2143,   4.2670,   0.1932,  -5.4529,   1.1423,
           2.7440,  -0.9985,   4.1561,  -2.4403,   4.7126,   3.8375,   0.5818,
          -1.0493,  -0.2357,   2.9981,  -2.7219],
        [ -3.5524,  -6.6008,   1.2448,   2.4274,  -8.6237,  -8.5913,   2.6999,
          -0.6147,  -7.8318,  -3.5772,   2.3370,   6.3394,  -0.1674,   6.1249,
          -4.0638,  -6.4690,   6.9843,   6.0075,   0.2291,  -6.0562,   2.4347,
           5.8197,  -2.0475,   6.3356,  -2.4510,   9.1627,   7.2650,   0.2359,
          -1.4253,  -2.2671,   3.8421,  -3.4459],
        [ -9.1979, -13.2224,   2.7821,  11.0999, -20.4358, -15.5342,   5.9197,
          -0.6128, -12.3522, -10.6518,   2.5861,  12.9167,  -1.8203,  16.2886,
          -9.5096,  -9.5816,  18.2942,  11.2289,   0.3367,  -7.8660,   6.3118,
          1

In [23]:
pos_enc = PositionEncoding2D(embed_dim=32,
                            grid_height=2,
                            grid_width=3,
                            dropout=0.0,
                            base=10000).pe[0]

In [24]:
pos_enc.shape

torch.Size([6, 32])

In [25]:
pos_enc

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  1.0000e+00],
        [ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  8.4147e-01,  5.4030e-01,  3.1098e-01,  9.5042e-01,
          9.9833e-02,  9.9500e-01,  3.1618e-02,  9.9950e-01,  9.9998e-03,
          9.9995e-01,  3.1623e-03,  9.9999e-01,  1.0000e-03,  1.0000e+00,
          3.1623e-04,  1.0000e+00],
        [ 0.0000e+00,  1.0000e+00,  0.00

In [26]:
norm = torch.nn.LayerNorm(32)

In [34]:
norm(img_patch_embed)

tensor([[-0.4514, -1.2892,  0.2878, -0.0801, -1.3793, -1.8687,  0.5630, -0.1268,
         -1.8834, -0.3125,  0.7560,  1.3383,  0.1805,  0.9046, -0.6293, -1.6085,
          1.0514,  1.3753,  0.1219, -1.6151,  0.4139,  0.9067, -0.2447,  1.3412,
         -0.6883,  1.5124,  1.2432,  0.2415, -0.2603, -0.0100,  0.9849, -0.7749],
        [-0.7134, -1.3166,  0.2357,  0.4697, -1.7168, -1.7104,  0.5237, -0.1322,
         -1.5601, -0.7183,  0.4519,  1.2438, -0.0437,  1.2013, -0.8146, -1.2905,
          1.3714,  1.1781,  0.0348, -1.2088,  0.4712,  1.1409, -0.4157,  1.2430,
         -0.4955,  1.8024,  1.4269,  0.0361, -0.2926, -0.4591,  0.7496, -0.6923],
        [-0.9070, -1.2713,  0.1774,  0.9303, -1.9243, -1.4806,  0.4614, -0.1299,
         -1.1926, -1.0387,  0.1596,  1.0948, -0.2392,  1.4000, -0.9353, -0.9418,
          1.5815,  0.9420, -0.0440, -0.7865,  0.4969,  1.2876, -0.5447,  1.0909,
         -0.2992,  1.9634,  1.5139, -0.1470, -0.3056, -0.8313,  0.5025, -0.5830],
        [-0.9287, -1.2610

In [35]:
torch.mean(img_patch_embed)

tensor(0.4379)